apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: nbmccc9eo-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nbmccc9eo-python 
  name: nbmccc9eo-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: nbmccc9eo-python 
