apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: nbmccc9eo-python 
  janus-idp.io/tekton: nbmccc9eo-python
  backstage.io/kubernetes-id: nbmccc9eo-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: nbmccc9eo-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml